FROM jenkins/jenkins:2.387.1
ENV JENKINS_UC_DOWNLOAD=http://ftp-nyc.osuosl.org/pub/jenkins/
COPY plugins.txt /usr/share/jenkins/ref/
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
## RUN jenkins-jobs --conf job-config-2.xml.j2 test