Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian10"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    config.vm.network "private_network", ip: "192.168.33.40"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
         vb.cpus   = 2
     end
     
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release gnome-core gnome
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant
    SHELL
end