apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wcg-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths: # | ImplementationSpecific
          - path: /svc1 # | Exact
            pathType: Prefix # <--| Prefix
            backend:
              service:
                name: wcg-service
                port:
                  number: 8888
