- hosts: jenkins.vm

  vars:
    jenkins_version: "2.73.1"
    jenkins_hostname: "192.168.50.5"
    jenkins_port: 8080
    jenkins_install_via: "apt"
    jenkins_jobs:
      - "my-first-job"
    jenkins_include_secrets: true
    jenkins_include_custom_files: true
    jenkins_custom_files:
      - src: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
        dest: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
    jenkins_plugins:
      - git
      - blueocean

  roles:
    - emmetog.jenkins