Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.define "jenkins.vm" do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.50.5"

        jenkins.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'jenkins.vm'
            ansible.inventory_path = "inventory"
        end
    end
end
