Vagrant.configure("2") do |config|
    config.vm.box = "betadots/centos8p7"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
    end

    config.vm.define "master.puppet", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.4", hostname: true
        master.vm.hostname = "master.puppet"

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'master'
            ansible.inventory_path = "inventory"
        end
    end

    config.vm.define "slave1.puppet" do |slave1|
        slave1.vm.network "private_network", ip: "192.168.50.5", hostname: true
        slave1.vm.hostname = "slave1.puppet"

        slave1.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'slave1'
            ansible.inventory_path = "inventory"
        end
    end

    config.vm.define "slave2.puppet" do |slave2|
        slave2.vm.network "private_network", ip: "192.168.50.6", hostname: true
        slave2.vm.hostname = "slave2.puppet"

        slave2.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'slave2'
            ansible.inventory_path = "inventory"
        end
    end

    config.vm.define "mineserver.puppet" do |mineserver|
        mineserver.vm.network "private_network", ip: "192.168.50.7", hostname: true
        mineserver.vm.hostname = "mineserver.puppet"

        mineserver.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'mineserver'
            ansible.inventory_path = "inventory"
        end
    end    
end
