Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.define "slave_html" do |slave_html|
        slave_html.vm.network "private_network", ip: "192.168.50.5"

        slave_html.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "slave_html.yaml"
            ansible.become = true
        end
    end

    config.vm.define "slave_php" do |slave_php|
        slave_php.vm.network "private_network", ip: "192.168.50.6"

        slave_php.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "slave_php.yaml"
            ansible.become = true
        end
    end

    config.vm.define "slave_nginx" do |slave_nginx|
        slave_nginx.vm.network "private_network", ip: "192.168.50.7"

        slave_nginx.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "slave_nginx.yaml"
            ansible.become = true
        end
    end    

    config.vm.define "master", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.4"

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
        end
    end
end
