Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
    end

    config.vm.define "slave.02ansible.1", primary: true do |slave|
        slave.vm.network "private_network", ip: "192.168.50.5"

        slave.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias la='ls -la'/g" /home/vagrant/.bashrc
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        SHELL
    end

    config.vm.define "master.02ansible.1", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.4"

        master.vm.provision "shell", inline: <<-SHELL
            apt-get install -y ansible vim mc sshpass
            apt-get update
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias la='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -la'" >> /root/.bashrc
            cp /vagrant/ansible.cfg /home/vagrant/ansible.cfg
            mkdir -p /home/vagrant/.ansible/tmp
            chown vagrant /home/vagrant/.ansible /home/vagrant/.ansible/tmp
            chmod 755 /home/vagrant/.ansible /home/vagrant/.ansible/tmp
            ansible --version
            cp /vagrant/inventory /home/vagrant/.ansible/inventory
            cp /vagrant/playbook.yaml /home/vagrant/.ansible/playbook.yaml 
        SHELL
    end

    #cd /home/vagrant/.ansible
    #ansible -i inventory all -m ping
    #ansible-playbook playbook.yaml -i inventory

end
