Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    config.vm.network "private_network", ip: "192.168.33.33"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    config.vm.network "forwarded_port", guest: 443, host: 443
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus   = 2
    end
  
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release zip mc
        
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant
    SHELL

    config.vm.provision "shell", inline: <<-SHELL
        apt-get install -y apt-transport-https
        mkdir /etc/apt/keyrings
        curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt-get install -y kubectl
    SHELL

    config.vm.provision "shell", inline: <<-SHELL
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dpkg -i minikube_latest_amd64.deb
    SHELL

end