apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wcg-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: wcg project
  sourceRepos:
    - "*"
  destinations:
    - server: "*"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
