Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"

  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.synced_folder "d:/cources/DevOps/Repo/devops-hometasks/01-vagrant", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "gitdemo.vagrant.vm"
      vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y mc
      sudo apt-get install -y git
      git --version
      git config --global user.name "vitaly.by"
      git config --global user.email "vitaly.by@gmail.com"
      git config --list
      sudo apt-get install -y apache2
      sudo apt-get install -y php
      wget https://github.com/vitalyby/devops-hometasks/archive/refs/heads/main.zip -O /tmp/git.zip
      unzip /tmp/git.zip
      sudo rm -ivf /var/www/html/index.html
      sudo cp ./devops-hometasks-main/01-vagrant/index.html /var/www/html/index.html
      sudo mkdir -p /var/www/html/php
      sudo cp ./devops-hometasks-main/01-vagrant/index.php /var/www/html/php/index.php
      sudo cp ./devops-hometasks-main/01-vagrant/ports.conf /etc/apache2/ports.conf
      sudo cp ./devops-hometasks-main/01-vagrant/httpd.conf /etc/httpd/conf/httpd.conf
      sudo cp ./devops-hometasks-main/01-vagrant/000-default.conf /etc/apache2/sites-enabled/000-default.conf
      sudo systemctl restart apache2
  SHELL

  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end