# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian10"
    config.vm.network "private_network", ip: "192.168.33.90"
    config.vm.network "forwarded_port", guest: 8081, host: 8091
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provision :ansible_local do |ans|
        ans.playbook = "nexus.yaml"
    end
end
